### ISSUE TITLE
LinkToken API Fails

### ISSUE THREAD

**Issue by Bwvolleyball** [merge-api/merge-sdk-kotlin#13]
SDK version: `v2.0.6`

Hello, when attempting to upgrade to the latest merge sdk kotlin, it seems that we cannot get link tokens anymore. I have verified the same API call via curl and it is working.

Example code:

```kotlin
    @Test
    fun `Can create a link token`() {
        val client = LinkTokenApi()
        client.setApiKey(MERGE_API_TOKEN)

        val result = runBlocking { client.linkTokenCreate(LinkTokenCreateRequest(EndUserDetailsRequest(
            endUserEmailAddress = "test1@mail.com",
            endUserOrganizationName = "organization1",
            endUserOriginId = "test1",
            categories = listOf(TICKETING),
            integration = "azure-devops"
        ))) }

        println(result)
    }
```

This cannot complete successfully and throws an exception:

<details>
  <summary>Expand for Exception</summary>

```java
io.ktor.serialization.JsonConvertException: Instantiation of [simple type, class dev.merge.client.ticketing.models.LinkToken] value failed for JSON property link_token due to missing (therefore NULL) value for creator parameter linkToken which is a non-nullable type
 at [Source: (InputStreamReader); line: 1, column: 49] (through reference chain: dev.merge.client.ticketing.models.LinkToken["link_token"])

	at |b|b|b(Coroutine boundary.|b(|b)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:138)
	at io.ktor.client.call.HttpClientCall.body(HttpClientCall.kt:87)
	at dev.merge.client.ticketing.apis.LinkTokenApi.linkTokenCreate$suspendImpl(LinkTokenApi.kt:127)
	at com.stackhawk.osprey.services.merge.MergeAzureDevopsTests$Work it$result$1.invokeSuspend(MergeAzureDevopsTests.kt:261)
	at |b|b|b(Coroutine creation stacktrace.|b(|b)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:122)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.stackhawk.osprey.services.merge.MergeAzureDevopsTests.Work it(MergeAzureDevopsTests.kt:261)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: io.ktor.serialization.JsonConvertException: Instantiation of [simple type, class dev.merge.client.ticketing.models.LinkToken] value failed for JSON property link_token due to missing (therefore NULL) value for creator parameter linkToken which is a non-nullable type
 at [Source: (InputStreamReader); line: 1, column: 49] (through reference chain: dev.merge.client.ticketing.models.LinkToken["link_token"])
	... 80 more
Caused by: io.ktor.serialization.JsonConvertException: Instantiation of [simple type, class dev.merge.client.ticketing.models.LinkToken] value failed for JSON property link_token due to missing (therefore NULL) value for creator parameter linkToken which is a non-nullable type
 at [Source: (InputStreamReader); line: 1, column: 49] (through reference chain: dev.merge.client.ticketing.models.LinkToken["link_token"])
	at io.ktor.serialization.jackson.JacksonConverter.deserialize(JacksonConverter.kt:52)
	at io.ktor.serialization.jackson.JacksonConverter$deserialize$1.invokeSuspend(JacksonConverter.kt)
	at |b|b|b(Coroutine boundary.|b(|b)
	at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:173)
	... 79 more
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class dev.merge.client.ticketing.models.LinkToken] value failed for JSON property link_token due to missing (therefore NULL) value for creator parameter linkToken which is a non-nullable type
 at [Source: (InputStreamReader); line: 1, column: 49] (through reference chain: dev.merge.client.ticketing.models.LinkToken["link_token"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:121)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:518)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3658)
	at io.ktor.serialization.jackson.JacksonConverter$deserialize$2.invokeSuspend(JacksonConverter.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
</details>

When I call this API directly via curl, I see what looks like a valid response, and so I'm not exactly sure what is going on here.

```bash
user $ curl -X POST https://api.merge.dev/api/ticketing/v1/link-token \                                                                                                                                                                                 
-H "Authorization: Bearer $MERGE_API_TOKEN" \
-H "Content-Type: application/json" \
-d '{"end_user_email_address":"test1@mail.com","end_user_organization_name":"organization1","end_user_origin_id": "test1","categories":["ticketing"],"integration": "azure-devops"}'

{"link_token":"z0t8q...<truncated>","integration_name":null,"magic_link_url":null}%
```

I attempted to debug the SDK, but didn't notice anything blatantly obvious. Are you able to assist with this issue?

**Comment by leewang0** [comment]
Hi @Bwvolleyball , neither the `LinkToken` model nor the `LinkTokenApi` class have changed since at least version `2.0.5`. One possibility is that the response you are currently getting is an error, which has a different payload. Our Kotlin SDK does not yet have good exception behavior, but I would recommend double checking the api key to start.

**Comment by Bwvolleyball** [comment]
Hi @leewang0 - that's why I also provided the curl with the same API key. I also agree that the object hasn't changed at all, which is why I was confused. If you run the provided unit test with a valid API key, I would expect it will fail for you as well on `v2.0.6` and it will pass on `v2.0.5`.

Under the covers, these are using 2 different APIs though - `v2.0.5` is using the old, and now undocumented `/create-link-token`, while `v2.0.6` is using `/link-token`

**Comment by leewang0** [comment]
Hi @Bwvolleyball , is it possible that you forked this package at some point in the past? I see nothing in the commit history of https://github.com/merge-api/merge-sdk-kotlin/commits/main/src/main/kotlin/dev/merge/client/ticketing/apis/LinkTokenApi.kt that would indicate it has ever hit `/create-link-token` , just trying to narrow down what could be happening here.

**Comment by Bwvolleyball** [comment]
Hi @leewang0 - no forks on our end.

I tried stepping through some of the very low-level http code from this library, and was able to extract this error message from the SDK: `{"common_models":["This field may not be null."]}`

If I change the request to this:

```kotlin
        val result = runBlocking {
            client.linkTokenCreate(
                LinkTokenCreateRequest(
                    EndUserDetailsRequest(
                        endUserEmailAddress = "test1@mail.com",
                        endUserOrganizationName = "organization1",
                        endUserOriginId = "test1",
                        categories = listOf(TICKETING),
                        integration = "azure-devops",
                        commonModels = listOf(),
                    )
                )
            )
        }
```
(addition is `commonModels = listOf()`)

then it seems to work.

However, since that field is required by the API, it feels like this SDK should set a default value OR make it a required parameter for request creation.

Looks like this is the value that was recently added to this request object that started causing this to fail. https://github.com/merge-api/merge-sdk-kotlin/pull/12/files#diff-ab9ab8c455a98cc7843a5fe1062b205ddb8b86d5a05c14791db5c60d0b523bc4R77

That definitely makes for a tricky upgrade experience, because we are hoping that we can trust new SDK versions.

**Comment by leewang0** [comment]
Hi @Bwvolleyball , thanks for the detailed report. I was going to do the stepping through of the base response like you said this morning, I really appreciate the extra info.

I've made a code change to allow for `null` in that property, it was an oversight on the API when we shipped it last month that conflicted only with the Kotlin SDK which has worse array-optional-property-behavior than the other code generators we use.

This fix will be out no later than 1pm Eastern on Monday 3/13, at which point your patch to the model in your code is unnecessary.

With regards to better backwards compatibility and testing, we are working on overhauling our SDKs to a new system that will give more guarantees, and we are also working on request and response logging that will let us pull this error from our end without you (or me) having to step through the response to get the actual root error. I apologize for the hassle this time, our SDKs are a work in progress.

**Comment by Bwvolleyball** [comment]
Hey @leewang0 - one thing that could help this SDK would be changing the global / default jackson serializer to simply ignore null values, if you think the API will be okay with that:

https://www.baeldung.com/jackson-ignore-null-fields#globally

I think this would have also avoided this issue, and should help unknown fields from creeping in in the future.

**Comment by leewang0** [comment]
@Bwvolleyball The API fix has been deployed that accepts the `null` value for the new property. I hesitate to add the global jackson rule, since I worry that will break in the case there is a model that distinguishes between explicit `null` and something else.

While I can't think of one right now, that doesn't mean this will never happen and disentangling THAT bug down the line could be very difficult as this incident scrolls out of human memory. I think it's far more likely we can add more strenuous code reviews on the API side to catch this backwards-incompatible nuance, rather than add that global rule which may break future models.

**Comment by Bwvolleyball** [comment]
Sounds good @leewang0 - thanks for working through this with me!
